---
all:
  children:
    proxmox_nodes:
      hosts:
        hip1tk-ppprox01:
          ansible_host: 192.168.11.11
        hip1tk-ppprox02:
          ansible_host: 192.168.11.12
        hip1tk-ppprox03:
          ansible_host: 192.168.11.13
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

    dns_servers:
      hosts:
        hip1tk-pvdns01:
          ansible_host: 192.168.11.53
        hip1tk-pvdns02:
          ansible_host: 192.168.11.54
      vars:
        ansible_user: bind-user
        ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
        ansible_become: true

    management_vms:
      hosts:
        hip1tk-pvdesk01:
          ansible_host: "{{ hostvars['hip1tk-pvdesk01']['ansible_default_ipv4']['address'] | default('192.168.11.100') }}"
      vars:
        ansible_user: "{{ lookup('env', 'USER') }}"
        ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
        ansible_connection: local
