---
all:
  children:
    proxmox_nodes:
      hosts:
        hip1tk-ppprox01:
          ansible_host: 192.168.11.11
        hip1tk-ppprox02:
          ansible_host: 192.168.11.12
        hip1tk-ppprox03:
          ansible_host: 192.168.11.13
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
