---
- name: restart patroni
  ansible.builtin.systemd:
    name: patroni
    state: restarted
  become: true

- name: reload patroni
  ansible.builtin.systemd:
    name: patroni
    state: reloaded
  become: true
