---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true

- name: restart php-fpm
  ansible.builtin.systemd:
    name: "php{{ php_version }}-fpm"
    state: restarted
  become: true

- name: reload php-fpm
  ansible.builtin.systemd:
    name: "php{{ php_version }}-fpm"
    state: reloaded
  become: true

- name: restart zabbix-agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
  become: true
